language: node_js
node_js:
  - "iojs"
  - "7"

branches:
  only:
  - gh-pages
  - master

script:
  - npm install
  - browserify -t brfs src/app.js -o dist/js/bundle.js
cache:
  directories:
    - "node_modules"
