language: node_js
node_js:
  - "iojs"

branches:
  only:
  - gh-pages
  - master

script:
  - npm install
  - browserify -t brfs src/app.js -o dist/js/bundle.js

cache:
  directories:
    - "node_modules"

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  on:
    branch: gh-pages
