name: Sanity checks

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Add pattern matcher
        run: echo "::add-matcher::${{ github.workspace }}/.github/problem-matchers.json"

      - name: Run sanity checks
        run: python ./scripts/PRsanitycheck.py
