name: Check Issue Format

on:
  issues:
    types: [opened, edited]

concurrency:
  group: ${{ github.event.issue.number }}
  cancel-in-progress: true

jobs:
  check-qt-registiration:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.labels.*.name, 'QuickTime')
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: stefanbuck/github-issue-parser@v3
        id: issue-parser
        with:
          template-path: .github/ISSUE_TEMPLATE/new-codepoint-qt.yml

      - name: Check QT Registration
        id: check-qt-registiration
        run: |
          fourcc=${{ steps.issue-parser.outputs.issueparser_fourcc }}
          if [[ ! $fourcc =~ ^[A-Z0-9\s]{4}$ ]]; then
              echo "fails=1" >> $GITHUB_OUTPUT
          fi

      - name: Find Comment
        uses: peter-evans/find-comment@v2
        id: fc
        with:
          issue-number: ${{ github.event.issue.number }}
          comment-author: "github-actions[bot]"
          body-includes: invalid codepoint

      - name: Create comment
        if: steps.check-qt-registiration.outputs.fails == '1'
        uses: peter-evans/create-or-update-comment@v3
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ github.event.issue.number }}
          edit-mode: replace
          body: |
            This registration request has invalid codepoint identifier. Please make sure the identifier is 4 characters long and only contains uppercase letters and numbers.
            - [ ] Correct identifier provided

      - name: Update comment
        uses: peter-evans/create-or-update-comment@v3
        if: steps.fc.outputs.comment-id != '' && steps.check-qt-registiration.outputs.fails != '1'
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            This registration request has invalid codepoint identifier. Please make sure the identifier is 4 characters long and only contains uppercase letters and numbers.
            - [x] Correct identifier provided
          edit-mode: replace
          reactions: rocket

  check-contact-info:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.labels.*.name, 'registration')
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: stefanbuck/github-issue-parser@v3
        id: issue-parser
        with:
          template-path: .github/ISSUE_TEMPLATE/new-codepoint-iso.yml

      - name: Find Comment
        uses: peter-evans/find-comment@v2
        id: fc
        with:
          issue-number: ${{ github.event.issue.number }}
          comment-author: "github-actions[bot]"
          body-includes: missing contact info

      - name: Create comment
        if: steps.issue-parser.outputs.issueparser_email == '' || steps.issue-parser.outputs.issueparser_phone == ''
        uses: peter-evans/create-or-update-comment@v3
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ github.event.issue.number }}
          edit-mode: replace
          body: |
            This registration request is missing contact information. We understand that you might not want to share your contact information publicly. In that case, please send an email to mp4reg [at] group.apple.com with a link to this issue.
