name: Publication to GitHub Pages

on:
  push:
    branches:
      - dev

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Git checkout
      uses: actions/checkout@v2

    - name: Use Node.js 8
      uses: actions/setup-node@v2
      with:
        node-version: '8'

    - run: npm install -g browserify
    - run: npm install
    - run: NODE_ENV=production browserify -t brfs src/app.js -o dist/js/bundle.js

    - name: Deploy to GitHub Pages
      #Note: if the repository name changes, the condition has to change 
      if: ${{ github.repository == 'mp4ra/mp4ra.github.io' }} 
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        folder: .
        branch: master  # deploying branch
        dry-run: True
